"""Fifth - added slug column to regions

Revision ID: 11bafb6dd3ff
Revises: 70e872b96087
Create Date: 2025-02-19 23:21:35.535624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bafb6dd3ff'
down_revision: Union[str, None] = '70e872b96087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituencies', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'constituencies', 'regions', ['region_id'], ['id'])
    op.add_column('regions', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_regions_slug'), 'regions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_slug'), table_name='regions')
    op.drop_column('regions', 'slug')
    op.drop_constraint(None, 'constituencies', type_='foreignkey')
    op.drop_column('constituencies', 'region_id')
    # ### end Alembic commands ###
