"""Modifications made to user and role models and schemas

Revision ID: 70e872b96087
Revises: 0b639d4cefe6
Create Date: 2025-02-18 13:13:41.558118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e872b96087'
down_revision: Union[str, None] = '0b639d4cefe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_index('ix_users_hashed_password', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_hashed_password', 'users', ['hashed_password'], unique=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
