"""Second Migration

Revision ID: fb8796515379
Revises: 01ce5d74e19b
Create Date: 2025-02-26 11:26:13.791159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8796515379'
down_revision: Union[str, None] = '01ce5d74e19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chiefdoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chiefdoms_id'), 'chiefdoms', ['id'], unique=False)
    op.create_index(op.f('ix_chiefdoms_name'), 'chiefdoms', ['name'], unique=True)
    op.create_index(op.f('ix_chiefdoms_slug'), 'chiefdoms', ['slug'], unique=True)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_organization'), 'users', ['organization'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_organization'), table_name='users')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_chiefdoms_slug'), table_name='chiefdoms')
    op.drop_index(op.f('ix_chiefdoms_name'), table_name='chiefdoms')
    op.drop_index(op.f('ix_chiefdoms_id'), table_name='chiefdoms')
    op.drop_table('chiefdoms')
    # ### end Alembic commands ###
